// Generated by https://quicktype.io
import 'dart:math';
import 'dart:core';

class Restos {
  List<Resto> items = new List();
  Restos();
  Restos.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    for (var item in jsonList) {
      final resto = new Resto.fromJsonMap(item);

      items.add(resto);
    }
  }
}

class Resto {
  String id;
  String name;
  String description;
  List<dynamic> category;
  double lat;
  double lng;
  String imageCover;
  String imageLogo;
  bool status;
  int phone;
  String email;
  String tipoCocina;
  dynamic calificacion;

  Resto({
    this.id,
    this.name,
    this.description,
    this.category,
    this.lat,
    this.lng,
    this.imageCover,
    this.imageLogo,
    this.status,
    this.phone,
    this.email,
    this.tipoCocina,
    this.calificacion,
  });

  Resto.fromJsonMap(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    description = json['description'];
    category = json['category'];
    lat = json['lat'] / 1;
    lng = json['lng'] / 1;
    imageCover = json['image_cover'];
    imageLogo = json['image_logo'];
    status = json['status'];
    phone = json['phone'];
    email = json['email'];
    tipoCocina = json['tipo_cocina'];
    calificacion = json['calificacion'];
  }
  getDecodeUtf8() {
    // if(tipoCocina != ""){
    //   var txt = tipoCocina.replaceAll("€", "");
    //   txt = txt.replaceAll("-", "");
    //   if(txt != ""){
    //     if(txt.substring(0,1) == " "){
    //       txt = txt.substring(2);
    //     }
    //     if(txt.substring(0,1) == ","){
    //       txt = txt.substring(1);
    //     }
    //     return txt;
    //   }
    // }

    // return "";
    return tipoCocina;
  }

  getCoverImg() {
    var url = imageCover.split(",");
    print(url[0]);
    if (imageCover == "") {
      return 'https://corporate.goldcar.es/wp-content/uploads/2018/05/image-not-available.png';
    } else {
      return '${url[0]}';
    }
  }

  getValorizar() {
    double cali = 0;
    if (calificacion != "") {
      cali = calificacion / 10;
    }
    return cali.toString();
  }

  getLatMeter() {
    var lat1 = lat;
    var lng1 = lng;
    var lat2 = 40.490220;
    var lng2 = -3.881900;
    var p = 0.017453292519943295;
    var c = cos;
    var a = 0.5 -
        c((lat2 - lat1) * p) / 2 +
        c(lat1 * p) * c(lat2 * p) * (1 - c((lng2 - lng1) * p)) / 2;
    var distanceBetween = 12742 * asin(sqrt(a));
    distanceBetween = num.parse(distanceBetween.toStringAsFixed(2));
    var roundedText = distanceBetween.toString() + ' km';
    return roundedText;
  }
}
