// Generated by https://quicktype.io
class Restos {
  List<Resto> items = new List();
  Restos();
  Restos.fromJsonList( List<dynamic> jsonList) {
    if (jsonList == null) return;
    
    for (var  item in jsonList) {
      final resto = new Resto.fromJsonMap(item);

      items.add(resto);
    }
  }
}

class Resto {
  String id;
  String name;
  String description;
  List<dynamic> category;
  double lat;
  double lng;
  String imageCover;
  String imageLogo;
  bool status;
  int phone;
  String email;

  Resto({
    this.id,
    this.name,
    this.description,
    this.category,
    this.lat,
    this.lng,
    this.imageCover,
    this.imageLogo,
    this.status,
    this.phone,
    this.email,
  });

  Resto.fromJsonMap(Map<String, dynamic> json) {
    id          = json['id'];
    name        = json['name'];
    description = json['description'];
    category    = json['category'];
    lat         = json['lat'] / 1;
    lng         = json['lng'] / 1;
    imageCover  = json['image_cover'];
    imageLogo   = json['image_logo'];
    status      = json['status'];
    phone       = json['phone'];
    email       = json['email'];
  }
}
